version: "3.0"
services:
    Active-NN:
        container_name: active-nn
        image: hsuan8169/hadoopha
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: active-nn
        ports:
            - 9870:9870
            - 10002:10002
        expose:
            - 9868
            - 8020
        command: bash -c "service ssh restart && sleep infinity"
    
    Standby-NN:
        container_name: standby-nn
        image: hsuan8169/hadoopha
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: standby-nn
        ports:
            - 9871:9870
        expose:
            - 9868
            - 8020
        command: bash -c "service ssh restart && sleep infinity"

    Active-RM:
        container_name: active-rm
        image: hsuan8169/hadoopha
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: active-rm
        ports:
            - 8088:8088
        expose:
            - 8030
            - 8031
            - 8032
            - 8033
        command: bash -c "service ssh restart && sleep infinity"
        
    Standby-RM:
        container_name: standby-rm
        image: hsuan8169/hadoopha
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: standby_rm
        ports:
            - 8089:8088
        expose:
            - 8030
            - 8031
            - 8032
            - 8033
        command: bash -c "service ssh restart && sleep infinity"
        
    
    HistorySever:
        container_name: historyserver
        image: hsuan8169/hadoopha
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: historyserver
        ports:
            - 19888:19888
        expose:
            - 10020
        command: bash -c "service ssh restart && sleep infinity"
    
    JournalNode1:
        container_name: journalnode1
        image: hsuan8169/journalnode1
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: journalnode1
        ports:
            - 8480:8480
        expose:
            - 2181
            - 2888
            - 3888
            - 8010
            - 8485
        command: bash -c "service ssh restart && sleep infinity"
    
    JournalNode2:
        container_name: journalnode2
        image: hsuan8169/journalnode2
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: journalnode2
        ports:
            - 8481:8480
        expose:
            - 2181
            - 2888
            - 3888
            - 8010
            - 8485
        command: bash -c "service ssh restart && sleep infinity"
    
    JournalNode3:
        container_name: journalnode3
        image: hsuan8169/journalnode3
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: journalnode3
        ports:
            - 8482:8480
        expose:
            - 2181
            - 2888
            - 3888
            - 8010
            - 8485
        command: bash -c "service ssh restart && sleep infinity"

    Worker1:
        container_name: worker1
        image: hsuan8169/workers
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: worker1
        expose:
            - 8040
            - 8042
            - 9864
            - 9866
            - 9867
            - 45454
        command: bash -c "service ssh restart && sleep infinity"

    Worker2:
        container_name: worker2
        image: hsuan8169/workers
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: worker2
        expose:
            - 8040
            - 8042
            - 9864
            - 9866
            - 9867
            - 45454
        command: bash -c "service ssh restart && sleep infinity"

    Worker3:
        container_name: worker3
        image: hsuan8169/workers
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: worker3
        expose:
            - 8040
            - 8042
            - 9864
            - 9866
            - 9867
            - 45454
        command: bash -c "service ssh restart && sleep infinity"
       
    
    Spark:
        container_name: spark
        image: hsuan8169/spark
        user: root
        privileged: true
        networks:
            - Hadoop_Cluster
        hostname: spark
        ports:
            - 8888:8888
            - 4040:4040
        expose:
            - 7077
        command: bash -c "service ssh restart && sleep infinity"

networks:
    Hadoop_Cluster:
        driver: bridge
