version: "3"
services:
    Active_NN:
        container_name: Active_NN
        build:
            context: ./Active_NN
            dockerfile: Dockerfile
        image: hsuan8169/active_nn
        networks:
            - Hadoop_Cluster
        ports:
            - 9870:9870
        command: bash -c "service ssh restart"
        stdin_open: true
        tty: true

    Active_RM:
        container_name: Active_RM
        build:
            context: ./Active_RM
            dockerfile: Dockerfile
        image: hsuan8169/active_rm
        networks:
            - Hadoop_Cluster
        ports:
            - 8088:8088
        command: bash -c "service ssh restart"
        stdin_open: true
        tty: true
    
    HistroySever:
        container_name: HistoryServer
        build:
            context: ./HistoryServer
            dockerfile: Dockerfile
        image: hsuan8169/historyserver
        networks:
            - Hadoop_Cluster
        ports:
            - 19888:19888
        command: bash -c "service ssh restart"
        stdin_open: true
        tty: true

    Worker1:
        container_name: Worker1
        build:
            context: ./Worker1
            dockerfile: Dockerfile
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        command: bash -c "service ssh restart"
        stdin_open: true
        tty: true

    Worker2:
        container_name: Worker2
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        command: bash -c "service ssh restart"
        stdin_open: true
        tty: true

    Worker3:
        container_name: Worker3
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        command: bash -c "service ssh restart"
        stdin_open: true
        tty: true

    Worker4:
        container_name: Worker4
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        command: bash -c "service ssh restart"
        stdin_open: true
        tty: true

    Worker5:
        container_name: Worker5
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        command: bash -c "service ssh restart"
        stdin_open: true
        tty: true
    
    Worker6:
        container_name: Worker6
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        command: bash -c "service ssh restart"
        stdin_open: true
        tty: true

networks:
    Hadoop_Cluster:
        driver: bridge
