version: "3"
services:
    Active_NN:
        container_name: Active_NN
        image: hsuan8169/active_nn
        networks:
            - Hadoop_Cluster
        ports:
            - 9870:9870
        stdin_open: true
        tty: true
        command: bash -c "service ssh restart" && /bin/bash/yes

    Active_RM:
        container_name: Active_RM
        image: hsuan8169/active_rm
        networks:
            - Hadoop_Cluster
        ports:
            - 8088:8088
        stdin_open: true
        tty: true
        command: bash -c "service ssh restart" && /bin/bash/yes
        
    
    HistroySever:
        container_name: HistoryServer
        image: hsuan8169/historyserver
        networks:
            - Hadoop_Cluster
        ports:
            - 19888:19888
        stdin_open: true
        tty: true
        command: bash -c "service ssh restart" && /bin/bash/yes

    Worker1:
        container_name: Worker1
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        stdin_open: true
        tty: true
        command: bash -c "service ssh restart" && /bin/bash/yes

    Worker2:
        container_name: Worker2
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        stdin_open: true
        tty: true
        command: bash -c "service ssh restart" && /bin/bash/yes

    Worker3:
        container_name: Worker3
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        stdin_open: true
        tty: true
        command: bash -c "service ssh restart" && /bin/bash/yes

    Worker4:
        container_name: Worker4
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        stdin_open: true
        tty: true
        command: bash -c "service ssh restart" && /bin/bash/yes

    Worker5:
        container_name: Worker5
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        stdin_open: true
        tty: true
        command: bash -c "service ssh restart" && /bin/bash/yes

    Worker6:
        container_name: Worker6
        image: hsuan8169/workers
        networks:
            - Hadoop_Cluster
        stdin_open: true
        tty: true
        command: bash -c "service ssh restart" && /bin/bash/yes

networks:
    Hadoop_Cluster:
        driver: bridge
